### ISSUE TITLE
Engine Test

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#391]

**Comment by yossigil** [comment]
The engine test submits S expressions to evaluate, apply, defun etc. To generate these S expressions 
you can use two techniques: String being parsed by the parser, or S expressions constructed manually.,
e.g., `(car '(a b)` can be generated  by parsing the string, or by `list(a, b).quote().car()` This makes it simpler to write complex tests, instead of using temporary variable.s
