### ISSUE TITLE
Design review: scope of setting

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#415]
There are too many counters and the logic of setting seems problematic. 

Can we do one main test to demonstrate what's needed?

**Comment by DorYeheskel** [comment]
@yossigil 
I did.
The logic of 2 counters are much better than storing 2 alists, and it works.

Please see the notes that I wrote you [here](https://github.com/yossigil/safot/issues/384).

**Comment by yossigil** [comment]
Not sure I got all this counters stuff right...
The trick is this, all sets are done to the *original* alist. Only bindings for function calls are done at the new list.
But, maybe I did not get the counters stuff corectly.

**Comment by DorYeheskel** [comment]
@yossigil 
This is exactly what I did with the counters.

**Comment by DorYeheskel** [comment]
# Design review:
**First**, let's assume that an error will occur during the call to `eval` at some point.

So, each `set` that occur during the `eval` until that error, we want to "free".

Because of the way that the a-list is built, "free" 1 set operation is done by cdr(). For example, free 1 set done by: "alist = alist.cdr()".

In the `error` function, we will call `restore_alist`, that all it does is "alist = alist.cdr()" N times, where N is the number of sets that we did until the error occur. In the end of `restore_alist`, the global set counter will set to 0.

**Second**, this solution creates new problem. As I said before, the global set counter will set to 0 only in `restore_alist`, which mean only if an error occur. We also want to set the global counter to 0 each time that `eval` function is finished, but eval is recursive, so we want to set the counter to 0 only in the end of the "top" eval call.

For that, we want to identify the "top" eval, and the way to do that can be done by global eval counter, that each time eval start, will increase by 1, and each time eval finish will decrease by 1, so the "top" eval will be only if the counter == zero in the end of the eval function. If this is the case, we will reset the global counter set to 0.



@yossigil

**Comment by yossigil** [comment]
I think there are two things to correct: if execution was aborted, all sets remain. Why shouldn't they? What's done, was done.
the second is that counters beat the idea of clean and simple code.

**Comment by yossigil** [comment]
OOPS, you are right, we agreed on restoring sets done during an aborted execution. Let's discuss this

**Comment by yossigil** [comment]
I think this can be resolved quickly, in a joint session. Let's try to make one soon.

**Comment by yossigil** [comment]
I will close this issue; I suggest another implementation in another issue.
