### ISSUE TITLE
Makefile in the testing folder broken

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#440]
Actually, it is not the makefile which is broken; there is something little with the installation of the tests.

![image](https://user-images.githubusercontent.com/12775400/127978864-1dc9ce35-c4c0-4b38-8ab4-13b193bcf140.png)

**Comment by DorYeheskel** [comment]
@yossigil 

I will create a setup script which will install python 3, pytest, define and will define all the environments, etc.

For now, the `SyntaxError` is because your python version < 2 ([format ](https://realpython.com/python-f-strings/) strings are python 3 +)
![image](https://user-images.githubusercontent.com/38854355/127979781-063d38e8-209f-4542-ae36-170fda71dec8.png)


The script run_all_tests.sh [check ](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/bin/run_all_tests.sh#L18)it and must failed before run, but setup file is better.

The `ImportError` happened because the PYTHONPATH need the path with the python files, I [did ](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/bin/run_all_tests.sh#L37)it too in the run_all_tests.sh

**Comment by yossigil** [comment]
Yes, I noticed this, but the script you use, requires Python3, but uses then the ordinary python....

Just add a goal to the makefile, name it `install`. I think this should be easy.

**Comment by DorYeheskel** [comment]
Done.
```bash
> make install -C ./Mini-Lisp.ShellTestFramework/build/
```

**Comment by yossigil** [comment]
Thanks
