### ISSUE TITLE
Mini-LISP JS - combine formals' a-list with global a-list

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#446]

**Comment by yossigil** [comment]
The basic idea is this.You maintain two pointers to the A-list. One point there is to the global A-list. The other point here is to be a list I think loads all the bindings. You release all bindings of formers when you return from a function. When you bind formals to actuals, you do that in the local a-list.  all set, defun, Nedfun go to the global a-list.

After a long discussion it was concluded to reverse the design decision @DorYeheskel ! We do not undo setting when a function aborts. They remain the same.

**Comment by OfirMarkowitz1** [comment]
An S expression can only be a one-sided list, so you if you only have a pointer to the globals' beginning, you won't be able to insert a preceding global while calling set/defun/ndefun. A possible solution is to maintain a pointer to the the last formal node instead. That is, the node that precedes the first global. This solution is a bit tricky, because there isn't always a last formal, because there isn't always formal bindings present in the A-list. So there's a lot of edge cases that need to be handled, and also you can't restore the list after the formals' bindings, as @yossigil and I discussed (get and set the A-list).
A favorable approach - always have a dummy node that separates the formals from the globals. Then, this node always exists, and you distinguish it from the other nodes by putting an atom (i.e. nil) as a value, instead of a pair, so the lookup can ignore it. This solution doesn't have edge cases and solves the problem of restoring the list after bind.

**Comment by yossigil** [comment]
Seems as if the dummy node is a good idea! But, you still need a condition in your code, to check if the item in the a-list is dummy or not; it is better to have the condition close to where it is used, e.g., a realisation of the above idea of two pointers like so; you augment the global a-list which is saved and restored with another pointer, called g (shot for globals); this pointer is nil when outside of every function; otherwise, it points to the last item in the a-list, just prior to globals.  If this pointer is nil; then you set into the current a-list. In total, you will have one test in the implementation of the primitive function set: if g is null; then you add to the a-list pointer and modify it as well. If it is not nil; you add **after** the g pointer, and modify the g pointer. Should be easy, I think.

**Comment by OfirMarkowitz1** [comment]
I'm not sure I'm following you. The dummy node does not contain a pair as its car but rather an atom (nil, for instance), thus easy to check if it's the dummy, and ignore. Then you just need to hold 2 pointers:
1. To the beginning of the a-list.
2. To the dummy node. This one actually never changes.
Whenever a set is performed, you just insert the new global after the dummy node.
Whenever binding of formals is performed, you insert them to the beginning of the list using the first pointer I mentioned.
Note for clarification: when the list is empty, both of the pointers will point to the dummy node.
I already implemented it and it's a very short and simple implementation, and it works :)

**Comment by yossigil** [comment]
I agree, you can do it with a dummy node; it is not every elegant though; you have to add the node to the search function, which should know about this implementation detail.

Let me explain first why we need the list to support two kinds of set operations. This is slightly different from the implementation in the book.  The book currently does not tell you how to solve the mystery of sets, in the REPL. With the REPL, if you do a set within one function, this set is saved for the next iteration; if this was not the case, then the set function would be meaningless. A correct implementation of REPL requires that if you do a set deep inside a function; this set will remain in effect when the function returns. We cannot distinguish between a direct call 
```lisp 
> (set ‘a 2)
``` 
and indirect call, 
```lisp 
> (cond (
  ((set ‘a 2) t)
)
``` 
If we make the distinction, then the user will be confused.  So, in the REPL, there are two kinds of SET. Global and local.
Global for setting variable, and local for making bindings. 

How about the book? Well the book makes a little lie. It ignores this subtle issue of the difference between argument binding and global bindings. All SET operations in the book are local. The little lie is that function SET is used in the book to define functions such as QUOTE, NDEFUN, and LAMBDA. But, the book does not deal with issue of evaluating two expressions in sequence, preserving the SETs made in the first expression to the evaluation in the second expressions. As far as the book is concerned, there is no way to do so, since the implementation of the a-list in the book does not support a distinction
 between local setting for binding, and global setting of variables. 

This is not a serious issue, and the book is fine in describing the implementation of EVAL, but no the implementation of REPLY. I consider adding a chapter to show how REPL can be implemented in MINI-LISP, if we add two primitives for READ and WRITE, but more importantly, by modifying the a-list as we do in the JS and Chic implementations. Yet another option is to implement the eval using what is known as continuation, in which recursion replaces sequential execution. 

The book makes a little lie on relying on the REPL to define functions. 
Once this is agreed, we can still decide whether an aborted execution undoes the sets done within it. But, since the SET operation is a global one, it makes no sense to undo it. 

Again, I suggest something along the following C++ (@DorYeheskel ) implementation
```C++
/** The interface of an a-list, in a file named “a-list.h”;  */
extern void set_global(S key, S value);  // Used for implementation of ordinary set
extern void set_local(S key, S value);    // Used for implementation of binding, a set which is erased.
extern S save(); // saves the a-list prior to local sets; the local sets are erased upon return and upon 
extern void restore(S); 
/** The implementation of an a-list, in a file named “a-list.h” */
S g = NIL;

void set(S key, S value) {
     set(key, value, g == NIL; 
}

**Comment by yossigil** [comment]
Ignore the above comment; it would not work; there is a subtle issue that we missed; and it may be the case that there is no way to solve the problem. Call me if you wish.

**Comment by yossigil** [comment]
I do not have access to a decent C++ environment, so, @DorYeheskel, do you suppose you could try this, perhaps in a different branch?

**Comment by OfirMarkowitz1** [comment]
This solution seems much less clear to me, and I think it will be difficult to follow for someone who tries to figure out the what's going on just by looking at the code. The pointer named "globals" are not actually pointing to the globals' unless the engine is the middle of evaluation of a lambda. This switching of the pointers meaning and the swaps between them is quite confusing.

An unrelated issue: the S-expression representation of a list is not according to convention, when inserting to the a_list (set and bind). In the unconventional use, the car part holds the next node while the cdr part holds the value.
The lookup actually expects the correct convention. If this passes the tests it will be very strange to me. If it does it probably means that a.cons(b) makes a pair of (b.a) instead of (a.b), which is wrong.

**Comment by yossigil** [comment]
Ok. Whatever. As long as the tests pass.

**Comment by OfirMarkowitz1** [comment]
It's pushed
